title: Lukas Rosenberger
description: Game Developer/Gameplay Programmer
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker
github:
  cv_url: cv.pdf
  curr_url: https://www.fh-salzburg.ac.at/en/studium/design-medien-und-kunst/master-multimediatechnology/curriculum
  email_url: mailto:lukas.rosenberger@hotmail.com

gems:
  - jekyll-mentions
